version: '2.2'
services:
  elasticsearch01:
    image: elasticsearch:7.5.1
    container_name: es01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.license.self_generated.type=basic
      - xpack.security.transport.ssl.enabled=true
    ports:
      - 9200:9200
    volumes:
      - /Users/shiguofu/data/es-7.5.1:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.5.1
    container_name: kibana
    links:
      - elasticsearch01
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch01:9200"
      ELASTICSEARCH_USERNAME: "kibana"
      ELASTICSEARCH_PASSWORD: "\"123456\""
    depends_on:
      - elasticsearch01
    ports:
      - 5601:5601

  apm-server:
    image: elastic/apm-server:7.5.1
    container_name: apm-server
    links:
      - elasticsearch01
      - kibana
    ports:
      - 8200:8200
    depends_on:
      - elasticsearch01
      - kibana
    command: apm-server -E output.elasticsearch.hosts=["elastic:123456@elasticsearch01:9200"]
