filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data/app_log/*/*.log

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~


output.logstash:
  hosts: ["logstash:5044"]
