version: '2.2'
services:
  jaeger-collector:
    image: "jaegertracing/jaeger-collector:1.22.0"
    container_name: jaeger-collector
    networks:
      - shiguofu_net
    external_links:
      - elasticsearch01
    environment:
      SPAN_STORAGE_TYPE: "elasticsearch"
      ES_SERVER_URLS: "http://elasticsearch01:9200"
      ES_USERNAME: "elastic"
      ES_PASSWORD: "123456"
    stdin_open: true
    ports:
      - 14268:14268
      - 14269:14269
      - 14250:14250
      - 14267:14267
      - 9411:9411

  jaeger-query:
    image: "jaegertracing/jaeger-query:1.22.0"
    container_name: jaeger-query
    networks:
      - shiguofu_net
    stdin_open: true
    environment:
      SPAN_STORAGE_TYPE: "elasticsearch"
      ES_SERVER_URLS: "http://elasticsearch01:9200"
      ES_USERNAME: "elastic"
      ES_PASSWORD: "123456"
    ports:
      - 16686:16686
      - 16687:16687

  jaeger-agent:
    image: "jaegertracing/jaeger-agent:1.22.0"
    container_name: jaeger-agent
    networks:
      - shiguofu_net
    stdin_open: true
    ports:
      - 5775:5775
      - 6831:6831/udp
      - 6832:6832
      - 5778:5778
    depends_on:
      - jaeger-collector
    links:
      - jaeger-collector
    command:
      - --reporter.grpc.host-port=jaeger-collector:14250

networks:
  shiguofu_net:
    external:
      name: docker-compose_default
