version: '2.2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - /Users/shiguofu/data/mysql57/logs:/var/log/mysql
      - /Users/shiguofu/data/mysql57/data:/var/lib/mysql
      - /Users/shiguofu/data/mysql57/conf:/etc/mysql
